#!/usr/bin/env python3
"""Build a minimal, environment-independent Vector config for `vector test`.

`vector test` loads the full config, but sources like kubernetes_logs,
docker_logs, journald or host_metrics cannot be built outside their native
environment (and `${VECTOR_SELF_NODE_NAME}` style interpolation fails when
the variable is unset). Unit tests only exercise transforms, so this script:

  1. extracts the `transforms:` section of a config verbatim,
  2. replaces every source referenced by a transform with a `demo_logs` stub
     (sources are never run by `vector test`),
  3. terminates every transform into a `blackhole` stub sink.

Stdlib only (no PyYAML) - it relies on the repo's config conventions:
top-level keys at column 0, transform names indented 2 spaces, and
`inputs:` given either flow style (`inputs: [a, b]`) or block style.

Usage: extract-transforms.py <config.yaml> > <test-config.yaml>
"""

import re
import sys


def extract_transforms_block(text):
    """Return the lines of the transforms: section (without the header)."""
    lines = text.splitlines()
    block = []
    in_block = False
    for line in lines:
        if re.match(r"^transforms:\s*$", line):
            in_block = True
            continue
        if in_block and line.strip() and not line.startswith((" ", "\t")):
            break  # next top-level key
        if in_block:
            block.append(line)
    return block


def transform_names(block_text):
    return re.findall(r"^  ([A-Za-z0-9_]+):\s*$", block_text, flags=re.M)


def referenced_inputs(block_text):
    refs = set()
    # Flow style: inputs: [a, b]
    for match in re.finditer(r"^\s+inputs:\s*\[([^\]]*)\]", block_text, flags=re.M):
        for name in match.group(1).split(","):
            name = name.strip().strip("\"'")
            if name:
                refs.add(name)
    # Block style:
    #   inputs:
    #     - a
    for match in re.finditer(
        r"^(\s+)inputs:\s*\n((?:\1[ \t]+-[^\n]*\n?)+)", block_text, flags=re.M
    ):
        for item in re.findall(r"-\s*([^\s#]+)", match.group(2)):
            refs.add(item.strip("\"'"))
    return refs


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: extract-transforms.py <config.yaml>")
    with open(sys.argv[1], "r", encoding="utf-8") as handle:
        text = handle.read()

    block = extract_transforms_block(text)
    if not any(line.strip() for line in block):
        sys.exit("error: no transforms: section found in %s" % sys.argv[1])
    block_text = "\n".join(block)

    names = transform_names(block_text)
    if not names:
        sys.exit("error: no transforms detected in %s" % sys.argv[1])
    sources = sorted(referenced_inputs(block_text) - set(names))

    out = []
    out.append("# Auto-generated by extract-transforms.py - do not edit")
    out.append("sources:")
    for source in sources:
        out.append("  %s:" % source)
        out.append("    type: demo_logs")
        out.append("    format: json")
        out.append("    interval: 60")
    out.append("")
    out.append("transforms:")
    out.append(block_text)
    out.append("")
    out.append("sinks:")
    out.append("  test_blackhole:")
    out.append("    type: blackhole")
    out.append("    inputs: [%s]" % ", ".join(names))
    print("\n".join(out))


if __name__ == "__main__":
    main()
